parameters:
#    stat_general.example.class: Stat\GeneralBundle\Example

services:
#    stat_general.example:
#        class: %stat_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
