Stat\GeneralBundle\Entity\Day:
    type: entity
    table: day 
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        game:
            type: string
            length: 255
        hit:
            type: integer
        uniq:
            type: integer
        newUsers:
            type: integer
            column: new_users
        transactionsCount:
            type: integer
            column: transactions_count
        money:
            type: integer
        payer:
            type: integer
        arpu:
            type: float
        arppu:
            type: float
        createdAt:
            type: datetime
            column: created_at
        bonusTime:
            type: integer
            column: bonus_time
        bonusTimeUniq:
            type: integer
            column: bonus_time_uniq 
    lifecycleCallbacks: {  }
